language: node_js

node_js:
  - 10
  - 12
  - 14
  - 15

matrix:
  include:
    - name: Lint
      node_js: lts/*
      script: npm run lint

script: npm run test:ci
after_success: <coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js
